# Generated by Django 3.0.8 on 2020-07-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('naics_code', models.IntegerField()),
                ('business_type', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('veteran', models.CharField(blank=True, max_length=100, null=True)),
                ('nonprofit', models.BooleanField(blank=True, null=True)),
                ('employee_lower_bound', models.IntegerField(blank=True, null=True)),
                ('employee_upper_bound', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loans_given', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_range', models.CharField(max_length=50)),
                ('jobs_retained', models.IntegerField(blank=True, null=True)),
                ('date_approved', models.DateField()),
            ],
        ),
    ]
