# Generated by Django 3.0.8 on 2020-07-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_range',
        ),
        migrations.AddField(
            model_name='loan',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppp.Business'),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppp.Lender'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_lower_bound',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_upper_bound',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
